apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{ values.name }}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  {%- if values.tags != "" %}
  tags: 
    {%- for tag in values.tags %}
    - ${{ tag }}
    {%- endfor %}
  {%- endif %}
spec:
  owner: ${{ values.owner }}
