{{- if eq .Values.environment "dev" }} # Deploy only in dev environment
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-virtual-service
spec:
  gateways:
    - mesh
  hosts:
    - {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-service.{{ .Values.appName }}-{{ .Values.environment }}.svc.cluster.local
  http:
    - route:
        - destination:
            host: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-service.{{ .Values.appName }}-{{ .Values.environment }}.svc.cluster.local
{{- end }}
