apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: meme-web-elasticache
  description: meme-web elasticache database
  annotations:
    backstage.io/techdocs-ref: dir:.
    # This annotation doesn't work in objects of kind Resource. It only works in objects of kind Component.
    # Our elasticache deployment is registered as a Resource in Backstege catalog, so we can't use this annotation unless we change the kind of the object to Component.
    # backstage.io/kubernetes-id: meme-web-elasticache
    # github.com/project-slug: AATT_GITHUB_USERNAME/backstage-minikube-lab-reloaded
    # argocd/app-selector: system-service=meme-web-elasticache # This is for Backstage ArgoCD plugin. You need to add this label in the application.yaml. You can also use argocd/app-name
    # grafana/dashboard-selector: "tags @> 'linux'" # The following selector will return dashboards that have a 'linux' tag
    # # grafana/overview-dashboard: 'http://localhost:8082/d/k8s_views_global/kubernetes-views-global' # I couldn't make this work. Got error: Refused to frame 'https://localhost:8082/' because it violates the following Content Security Policy directive: "frame-src 'self' http://localhost:8082".
  tags:
    - elasticache 
  links:
    - title: Documentation
      url: https://github.com/AATT_GITHUB_USERNAME/automate-all-the-things-transcendence
    - title: Admin Dashboard
      type: admin-dashboard
      icon: dashboard
      url: https://admin.example-org.com
    - title: Metrics
      type: metrics-dashboard
      icon: analytics
      url: https://grafana.domain.com/
    - title: Logs
      type: logs-dashboard  
      icon: assignment
      url: https://grafana.domain.com/
spec:
  type: database
  lifecycle: production
  owner: meme-web-elasticache-subteam
  system: meme-web
