# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     # external-dns.alpha.kubernetes.io/hostname: grafana
#   name: manual-lb
# spec:
#   ports:
#   - name: service
#     port: 80
#     protocol: TCP
#     targetPort: 3000
#   - name: https
#     port: 443
#     protocol: TCP
#     targetPort: 3000
#   selector:
#     app.kubernetes.io/instance: grafana
#     app.kubernetes.io/name: grafana
#   type: LoadBalancer
#   # tls:
#   #   - secretName: grafana-ingress-certificate