apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: aatt-demo-eks-cluster
spec:
  forProvider:
    region: us-east-1
    version: "1.29"
    roleArnRef:
      name: aatt-demo-eks-controlplane-role
    vpcConfig:
      - endpointPublicAccess: true
        endpointPrivateAccess: false 
        subnetIdRefs:
          - name: aatt-demo-private-subnet-b
          - name: aatt-demo-private-subnet-c
    tags:
      Name: aatt-demo-eks-cluster
  providerConfigRef:
    name: aws