apiVersion: v1
appVersion: 0.28.1
description: Flagger's load testing services based on rakyll/hey and bojand/ghz that
  generates traffic during canary analysis when configured as a webhook.
home: https://docs.flagger.app
icon: https://raw.githubusercontent.com/fluxcd/flagger/main/docs/logo/flagger-icon.png
keywords:
- flagger
- istio
- appmesh
- linkerd
- gloo
- osm
- smi
- gitops
- load testing
kubeVersion: '>=1.19.0-0'
maintainers:
- email: stefanprodan@users.noreply.github.com
  name: stefanprodan
  url: https://github.com/stefanprodan
name: loadtester
sources:
- https://github.com/fluxcd/flagger
version: 0.28.1
