apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: new-backstage-system
  title: New Backstage System
  description: Create new Backstage system
  tags:
    - backstage
spec:
  owner: web@example.com
  type: component
  parameters:

    ###############################################################################################################
    # First page
    - title: Provide some simple information
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Name of the new system
          ui:field: EntityNamePicker
          pattern: '^[a-z0-9-]+$' # Only lowercase letters, numbers and hyphens
          maxLength: 30
          ui:help: 'Use only lowercase letters, numbers and hyphens. Max length: 30 characters.'  

        description:
          title: Description
          type: string
          description: Help others understand what this system is for.
          minLength: 10
          ui:help: 'Make it descriptive! At least 10 characters.'

        owner:
          title: Owner
          type: string
          description: Owner of the service.
          ui:field: OwnerPicker
          ui:options:
            catalogFilter: # This uses the value "group:default/meme-web-team"
              - kind: Group
              
        tags:
          title: Tags
          type: array
          items:
            type: string
          description: Tags associated with the system

    ###############################################################################################################
    # Second page
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            # allowedOrganizations: # This doesn't get displayed as a dropdown list like allowedRepos does, IDK why.
            #   - AATT_DOCKERHUB_USERNAME
            #   - AATT_DOCKERHUB_USERNAME
            allowedRepos:
              - automate-all-the-things-braindamage
              - automate-all-the-things-transcendence
              - automate-all-the-things-nirvana
              - automate-all-the-things-almighty

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          tags: ${{ parameters.tags }}

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        allowedHosts: ['github.com']
        repoUrl: ${{ parameters.repoUrl }}
        title: "Create new system: ${{ parameters.name }}"
        branchName: create-system-${{ parameters.name }}
        description: |
          # New system: ${{ parameters.name }}

          ${{ parameters.description if parameters.description }}
        targetPath: backstage/entities/systems
        
  output:
    links:
      - url: ${{ steps.publish.output.remoteUrl }}
        title: "Go to PR"
