apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: istio-staging-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    # Let’s Encrypt has a strict rate limit on certificates issued, so we use the Staging Let’s Encrypt server for testing, and then we switch to the Production Let’s Encrypt server.
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      # Reference to Staging secret
      name: istio-staging-issuer
    solvers:
      - selector: {}
        http01:
          ingress:
            class: istio