cr:
  create: true
  spec:
    auth:
      strategy: "anonymous" # Don't require password to log in
    external_services:
      prometheus:
        url: "http://kube-prometheus-stack-prometheus.observability:9090/"
      # grafana:
      #   enabled: true
      #   in_cluster_url: 'http://grafana.observability:3000/'
  # deployment:
  #   ingress:
  #     enabled: true
  #     override_yaml:
  #       metadata: {
  #         annotations: {    
  #           kubernetes.io/ingress.class: alb,
  #           alb.ingress.kubernetes.io/scheme: internet-facing,
  #           alb.ingress.kubernetes.io/target-type: ip,
  #           alb.ingress.kubernetes.io/healthcheck-protocol: HTTP,
  #           alb.ingress.kubernetes.io/healthcheck-port: traffic-port,
  #           alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15',
  #           alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5',
  #           alb.ingress.kubernetes.io/success-codes: '200',
  #           alb.ingress.kubernetes.io/healthy-threshold-count: '2',
  #           alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  #         }
  #       }

ingress:
  host: kiali.AATT_USER_EMAIL # This value was modified by the initial-setup python script

  annotations: 
    # External-DNS related annotations
    external-dns.alpha.kubernetes.io/hostname: kiali.AATT_USER_EMAIL

    # ALB related annotations
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  
    # TLS related annotations
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn:  # This value was modified by the deploy-infra pipeline