global:
  istioNamespace: service-mesh

# This creates issues with terraform destroy
# service:
#   annotations: {    
#     service.beta.kubernetes.io/aws-load-balancer-type: nlb # This is to use a Network Load Balancer (NLB) instead of the default Classic/Elastic Load Balancer (ELB). 
#   }
