apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-auth-token
spec:
  encryptedData:
    ARGOCD_AUTH_TOKEN: {{ .Values.argocdAuthToken }}
  template:
    metadata:
      name: argocd-auth-token
      namespace: {{ include "common.names.fullname" . }}
    type: Opaque