apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-secret
spec:
  encryptedData:
    GITHUB_TOKEN: {{ .Values.githubToken }}
    AUTH_GITHUB_CLIENT_ID: {{ .Values.githubAuthClientId }}
    AUTH_GITHUB_CLIENT_SECRET: {{ .Values.githubAuthClientSecret }}
  template:
    metadata:
      name: github-secret
      namespace: {{ include "common.names.fullname" . }}
    type: Opaque