apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-token
spec:
  encryptedData:
    GRAFANA_TOKEN: {{ .Values.grafanaToken }}
  template:
    metadata:
      name: grafana-token
      namespace: {{ include "common.names.fullname" . }}
    type: Opaque