# Had to modify values.schema.json to incorporate these three values
host: AATT_DOMAIN # This value was modified by the initial-setup python script
email: AATT_USER_EMAIL # This value was modified by the initial-setup python script

issuer: staging # Options are "staging" and "production"

global:
  istioNamespace: service-mesh

service:
  annotations: 
    external-dns.alpha.kubernetes.io/hostname: "AATT_DOMAIN,dev.AATT_DOMAIN,stage.AATT_DOMAIN" # This value was modified by the initial-setup python script
  
