meshProvider: "istio"

metricsServer: http://kube-prometheus-stack-prometheus.observability:9090/ # URL:port.namespace

# Creates serviceMonitor for monitoring Flagger metrics
serviceMonitor:
  enabled: true
  labels: {    
    release: kube-prometheus-stack # Required label to be scraped by Prometheus
  }
