apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-nginx-conf-configmap
data:
  nginx.conf: {{ .Values.configmap.nginxConf | toYaml | indent 1 }}
