apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-images-configmap
data:
  memes.js: {{ .Values.configmap.images | toYaml | indent 1 }}
