apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}
      {{- range $key, $value := .Values.deployment.labels }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}
        {{- range $key, $value := .Values.deployment.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          # We specify resources now because we are using Horizontal Pod Autoscalers
          resources:
            requests:
              memory: "5Mi"
              cpu: "50m"
            limits:
              memory: "50Mi"
              cpu: "200m"
          volumeMounts:
            - name: images-configmap
              mountPath: /usr/share/nginx/html/resources
            - name: nginx-conf-configmap
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: images-configmap
          configMap:
            name: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-images-configmap
        - name: nginx-conf-configmap
          configMap:
            name: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-nginx-conf-configmap
