appName: AATT_APP_NAME # This value was modified by the initial-setup python script

service: backend

containerPort: 3000 # Port where the app in the container exposes the service

deployment:
  labels: {    
    istio: monitor # This label is used by the PodMonitor
  }
  image:
    repository: harbor.AATT_USER_EMAIL/AATT_APP_NAME/backend # This value was modified by the initial-setup python script