cr:
  create: true
  spec:
    auth:
      strategy: "anonymous" # Don't require password to log in
    external_services:
      prometheus:
        url: "http://kube-prometheus-stack-prometheus.observability:9090/"
      # grafana:
      #   enabled: true
      #   in_cluster_url: 'http://grafana.observability:3000/'
  # deployment:
  #   ingress:
  #     enabled: true
  #     override_yaml:
  #       metadata: {
  #         annotations: {    
  #           kubernetes.io/ingress.class: alb,
  #           alb.ingress.kubernetes.io/scheme: internet-facing,
  #           alb.ingress.kubernetes.io/target-type: ip,
  #           alb.ingress.kubernetes.io/healthcheck-protocol: HTTP,
  #           alb.ingress.kubernetes.io/healthcheck-port: traffic-port,
  #           alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15',
  #           alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5',
  #           alb.ingress.kubernetes.io/success-codes: '200',
  #           alb.ingress.kubernetes.io/healthy-threshold-count: '2',
  #           alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  #         }
  #       }

ingress:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
