# Default user is "admin"
harborAdminPassword: automate-all-the-things

expose:
  tls:
    enabled: false
    
  ingress:
    hosts:
      core: harbor.AATT_DOMAIN # This value was modified by the harbor-setup pipeline
    
    controller: alb

    annotations: 
      # External-DNS related annotations
      external-dns.alpha.kubernetes.io/hostname: harbor.AATT_DOMAIN # This value was modified by the initial-setup python script 

      # ALB related annotations
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
      alb.ingress.kubernetes.io/success-codes: '200'
      alb.ingress.kubernetes.io/healthy-threshold-count: '2'
      alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'

      # TLS related annotations
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/certificate-arn:  # This value was modified by the deploy-infra pipeline
    
externalURL: https://harbor.AATT_DOMAIN # This value was modified by the initial-setup python script

