site_name: ${{ values.system }}-${{ values.service }} documentation
nav:
  - Home: index.md
  - API: api.md
  - Deployment: deployment.md
theme:
  name: 'material'
plugins:
  - search
docs_dir: 'docs'
