apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-images-configmap
data:
  memes.js: {{ .Values.configmap.images | toYaml | indent 1 }}
