apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-hpa
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # We have no canary in dev environment, so if the env is dev, the value of name will be <my-app-name>-backend-stage-deployment, else it will be <my-app-name>-backend-stage-deployment-primary
    name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}{{ if eq .Values.environment "dev" }}-deployment{{ else }}-deployment-primary{{ end }}
  targetCPUUtilizationPercentage: 80
  # targetCPUUtilizationPercentage: 1 # Uncomment this and comment the line above to test the Horizontal Pod Autoscaler