{{- if eq .Values.environment "dev" }} # Deploy only in dev environment
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-service
spec:
  selector:
    full-name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  type: ClusterIP
{{- end }}
