apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: AATT_APP_NAME-back-stage # This value was modified by the initial-setup python script
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Adding the finalizer enables cascading deletes when implementing the App of Apps pattern. If this isn't used, when you remove the application yaml from git, the application will be removed from ArgoCD but the resources will remain active in the cluster
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: AATT_APP_NAME-stage # This value was modified by the initial-setup python script
    server: https://kubernetes.default.svc
  project: my-app
  source:
    path: helm/my-app/backend
    helm:
      valueFiles:
        - environments/values-stage.yaml
    repoURL: https://github.com/AATT_GITHUB_USERNAME/automate-all-the-things-transcendence.git # This value was modified by the initial-setup python script
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
