apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-gateway
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
      # If environment is prod, then the value will be just <.Values.host> and not <.Values.environment>.<.Values.host>
        - {{ if eq .Values.environment "prod" }}{{ .Values.host }}{{ else }}{{ .Values.environment }}.{{ .Values.host }}{{ end }}
    {{- if eq .Values.environment "prod" }} # HTTPS only in prod
      # tls:
      #   httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ .Values.host }}
      tls:
        mode: SIMPLE
        credentialName: istio-gateway-certificate # This should match the Certificate secretName
    {{- end }}


# apiVersion: networking.istio.io/v1beta1
# kind: Gateway
# metadata:
#   name: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-gateway
#   {{- if eq .Values.environment "prod" }} # HTTPS only in prod
#   annotations:
#     cert-manager.io/cluster-issuer: staging-cluster-issuer
#   {{- end }}
# spec:
#   {{- if ne .Values.environment "prod" }} 
#   selector:
#     istio: gateway
#   servers:
#     - port:
#         number: 80
#         name: http
#         protocol: HTTP
#       hosts:
#         - {{ .Values.environment }}.{{ .Values.host }}
#   {{- end }}
#   {{- if eq .Values.environment "prod" }} 
#   selector:
#     istio: gateway
#   servers:
#     - port:
#         number: 80
#         name: http
#         protocol: HTTP
#       hosts:
#         - {{ .Values.host }}
#       tls:
#         httpsRedirect: true
#     - port:
#         number: 443
#         name: https
#         protocol: HTTPS
#       hosts:
#         - {{ .Values.host }}
#       tls:
#         mode: SIMPLE
#         credentialName: {{ .Values.appName }}-com-crt # This should match the Certificate secretName
#   # gatewayClassName: foo
#   listeners:
#     - hostname: {{ .Values.host }}
#       port: 443
#       protocol: HTTPS
#       routes:
#         kind: HTTPRoute
#         selector:
#           matchLabels:
#             # app: foo
#             istio: gateway
#       tls:
#         mode: Terminate
#         certificateRef:
#           name: {{ .Values.appName }}-com-crt
#           kind: Secret
#           group: core
#   {{- end }}