{{- if eq .Values.environment "dev" }} # Deploy only in dev environment
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-virtual-service
spec:
  gateways:
    - {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-gateway
  hosts:
    - {{ .Values.environment }}.{{ .Values.host }}
    # - {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-service
    - {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-service.{{ .Values.appName }}-{{ .Values.environment }}.svc.cluster.local
  http:
    - route:
        - destination:
            host: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-service.{{ .Values.appName }}-{{ .Values.environment }}.svc.cluster.local
      # match:
      #   - uri:
      #       prefix: "/"
{{- end }}

# {{- if eq .Values.environment "dev" }} # Deploy only in dev environment
# apiVersion: networking.istio.io/v1beta1
# kind: VirtualService
# metadata:
#   name: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-virtual-service
# spec:
#   gateways:
#     - {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-gateway
#   hosts:
#     - {{ .Values.host }}
#     # - {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-service
#     - {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-service.{{ .Values.appName }}-{{ .Values.environment }}.svc.cluster.local
#   http:
#     - match:
#         - uri:
#             prefix: /{{ .Values.environment }}/
#             # prefix: /{{ .Values.environment }}
#       rewrite:
#         uri: /
#       route:
#         - destination:
#             host: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-service.{{ .Values.appName }}-{{ .Values.environment }}.svc.cluster.local
# {{- end }}
