apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Adding the finalizer enables cascading deletes when implementing the App of Apps pattern. If this isn't used, when you remove the application yaml from git, the application will be removed from ArgoCD but the resources will remain active in the cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc  
  project: sealed-secrets
  source:
    path: helm/infra/sealed-secrets
    helm:
      valueFiles:
        - values-custom.yaml
    repoURL: https://github.com/tomasferrarisenda/automate-all-the-things-transcendence.git # This value was modified by the initial-setup python script
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
