apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}
      {{- range $key, $value := .Values.deployment.labels }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}
        {{- range $key, $value := .Values.deployment.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          # We specify resources now because we are using Horizontal Pod Autoscalers
          resources:
            requests:
              memory: "5Mi"
              cpu: "50m"
            limits:
              memory: "50Mi"
              cpu: "200m"
          env:
            - name: SERVICE
              value: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}
            - name: REDIS_HOST
              value: {{ .Values.redis_host }} 
            - name: JAEGER_HOST
              value: jaeger-collector.observability
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASS
      # TRANSENDANCE
      # imagePullSecrets:
      # - name: harbor-credentials

