{{- if eq .Values.environment "prod" }} # Deploy only in prod environment
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials-prod
  namespace: gonchi-prod
spec:
  encryptedData:
    .dockerconfigjson: AgA9GW9JvWwNu8LMwBE/36gdMPLadLLo+fra4m1wsCZocPTrKb4VfkVNi6qohWo2OuIB/rx1zLZN/u7U+LGnCl3ywrNaPSWNSHrtGYrgehfZFLnPYB9NEvkc/gAO7xqWKUEzk60Y8ZYhtionZ7EZpp6FcnZxli+UzO0R8z3mikoh+/WnJslQ8PnwXEP7BnzyRFZuTiD3MpmmlUqD/DmFAx4jxBQ+6qN3i8omxB2cpgFbnHiHn2R3rKu1i3m21K+QO4x3Q0EeyxMbHmRkWvz7+Fi8LHOp0N0eqf3ZNidnVGBy2P+GmwE1qEDEw8IIeRy5H1mQxzgu6CBh8gmX1fa5PRF1VH2iIMae/xrAtXcKtAg+9eIA28MG0TP21qydygde2eT1ie9qPnTvn5xk1zl+1LbCJqgmxzr/nXoBSMaw79F8+vzEsLQQDG2ERaaLfaW89GRmdqY3I27ShYN5OLecEqUSEyjo7GQOswgye+qWEatT01a9DHrI31tAl//tWGfOqkreUfghKCmCrIfSXQEJtLBgw7ANbfEUaFFruUxfP5oOPkcAUXlJMNAnpDZAFhFTCLbsYYX9BY3MPu5hHG9wNKzkV21J/1JXz4Qp0Mw87apGJtIK8z2e7OghgSSjimtECtZRpxfFyhILXV8+jbnivN0XPH1oxmYchCKc1bgzcrKbs2uG4aiZv+L+f1gj4yOthWmiGSEUXELtZC5+tl0kLof3tNIFhf6vuqbb84W0W7tt4I7SBMvN6ly+ITYhS0Lr4mifmqZiFWLIc6fngtb15frWxduUQpYlAuELEz8Q2wHVjfZ/SBuA2E5eQjyeP/SoOABB+DAbDMPJxgv3W/IVmmmYVIqfUTSuLw==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials-prod
      namespace: gonchi-prod
    type: kubernetes.io/dockerconfigjson
---
{{- end }}
