{{- if eq .Values.environment "dev" }} # Deploy only in dev environment
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials-dev
  namespace: gonchi-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAaW8uZZiNhp8logcMmUZtwokDe7KzxLJEI2s2iyWK2jMpc9dCVYcLTVxHv8YgNxUMnXuM+Rv+U65kJUzxumPiZBVaAzGfsK1ebmG7yR1A7npiwJB5WIgpIzige17Sflf7hJR4TzxvxADj7B+C/kmtuNWAvgSIqHz5kN6T8zmtOsx7oXCAwOduwMDqlJmThrcE+W2YVn4jB1oXOthna8sC0CboO6CqqXIEFsVY+BzZ9svO1DzbPYTXQwa5bsGd385uJfJZKAKfpfvCyR+nSxGlSDgq2zHknUzxwcXn20phKE2zzBMz3F23JLV7MtkUaa7P59um7Ps2GzfIhi1XXK4QyuisIAmxN1mQWHm64TWcJ1Sn01E863so/WTit6rpm56y2a2cjsO/E5FhcgcVo0sG/YmNuLkfiyCz5X7YtRV3+SMMc4N1fGId1BGlwQ9wPkmPz6a8iQE2sv4LzpshsYvCs/glfOlZV4UXlf3ItgdX1/2Gdb5oKjHcCpE+l0xSukXDoJmYCb13cfEILOT1K1MUIDcE4mTd99Svge0uDKdaUrcPErWHjZlggWqXtmvMSEMH+QJ4FxBZaucl1EQLR+ii4aXNZ6FvII1MWaGdreu7Un2zmjf3LOrNqD75YftQZtasz0wETARDiFtyuHQFXcmR3ZqpkiqaYRuawotulZIQaceMf/ogAqI1TEYIuD3hojjxjaXlunG/kpKvgN9do5nFOyl8g18qTIXBh+BpbEPF5ZgyZ3IQlOvnBWLsOo+bsQosjxrFceaX19ZaRLZQzIGe0kvD12O2pNA3Qx/ywt1dr5pt2khTNDyC9PXDtfgJO2sS1znzd2i2iO2WObOiHHYijSuQVkgEJDw==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials-dev
      namespace: gonchi-dev
    type: kubernetes.io/dockerconfigjson
---
{{- end }}
