{{- if eq .Values.environment "stage" }} # Deploy only in stage environment
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials-stage
  namespace: gonchi-stage
spec:
  encryptedData:
    .dockerconfigjson: AgCVTYca874F7nN10FjSYD6PnOYiSe/21dcdoLbddDp2zhVbt+Bo3FBEakn8oDqAs0TlwdqLKYAjVt7WT8Vt+UHfIeDI+k+CF/H5PgrGLnl0OfZpTrMB/Ea5T225w0TGT6jPr5H3MQ5cEweEI6zMzAh1UdSi+Gt5PeK5ECyGWyOiY/k1/RMOTRix/2gYcYyFufSM1Xml5U3qVEs89GBRMdWP6IqM826nyhkkWXtcS4qWmonbOy8jP2/oaO9Y5qksfyEzXIhQlIf5eQbyZ/oV2FUKhzzU2mEVqcqeFXZI6UvsTqV3g5u3uuWVb6akUyiD/8gG2SI5ZqKQ0wh1DZQK17HVbFQPROj3fZTRFyGrucHfY/Pp78s9NkV7RtFlUapuvClROllPHukdg9B3/cTJjjo5B1xPSmagzBw21pz1zTw4uiArGMMKzi9sKRcH4AhzJZ6Y5ICBXxrujjlC3+RGoR+93WuT+5peIZdti/SLfbOAsvrYvmBMFC0j2MzHmHrfwsUT1Wb2RSu61Suizp+yJyVCh7xbnrBkyY7iJr4XyIEuBID+whETaCO6TOejwLABmhhbku1YsvJSzRtNsooRbFPRDnE0XRM0xj4M3ooe29skou2yBqZ4JklItwsK+sPjBYX1yCK+RBmljCAQIXkNgMjSkyd6xI7hjXyWStAVKUW6XwpluMoT6z6LiyI8ySGqTqFquodUk/IqiMQHNwgmfgkv/me7tKnvRi9vctGYGXItAlMgTSdd5ejubJoibZHnx/rUFOuwtUXc0ELR707QNsZdysvijeLU75Fk1YTy2U6Zr6N8ZHhS0TTgHuQROcG6PBmEFTCHwYAO8WmuM2zEM5gLtdA82ZJuug==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials-stage
      namespace: gonchi-stage
    type: kubernetes.io/dockerconfigjson
---
{{- end }}
