apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    REDIS_PASS: {{ .Values.secret.redis_pass }}
  template:
    metadata:
      name: redis-secret
      namespace: {{ .Values.appName }}-{{ .Values.environment }}
    type: Opaque