{{- if eq .Values.environment "dev" }} # Deploy only in dev environment
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-service
spec:
  selector:
    app: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}
  ports:
    - protocol: TCP
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
  type: ClusterIP
{{- end }}

