apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: aatt-demo-private-subnet-b
spec:
  forProvider:
    availabilityZone: us-east-1b
    cidrBlock: 10.0.64.0/19
    region: us-east-1
    vpcIdRef: 
      name: aatt-demo-vpc
    tags:
      Name: aatt-demo-private-subnet-b
      kubernetes.io/role/internal-elb: "1" # Required for EKS
      kubernetes.io/cluster/${var.project}-cluster: "owned" # Required for EKS
  providerConfigRef:
    name: aws
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: aatt-demo-rta-private-b
spec:
  forProvider:
    region: us-east-1
    subnetIdRef:
      name: aatt-demo-private-subnet-b
    routeTableIdRef:
      name: aatt-demo-route-table-private-b
    tags:
      Name: aatt-demo-rta-private-b
  providerConfigRef:
    name: aws