apiVersion: ec2.aws.upbound.io/v1beta1
kind: NATGateway
metadata:
  name: aatt-demo-nat-gw-c
spec:
  forProvider:
    region: us-east-1
    subnetIdRef: 
      name: aatt-demo-public-subnet-c
    allocationIdRef:
      name: aatt-demo-eip-c
    tags:
      Name: aatt-demo-nat-gw-c
  providerConfigRef:
    name: aws
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: EIP
metadata:
  name: aatt-demo-eip-c
spec:
  forProvider:
    region: us-east-1
    vpc: true
    tags:
      Name: aatt-demo-eip-c
  providerConfigRef:
    name: aws