# This binds AWS's IAM with Kubernetes's RBAC. It allows Kubernetes to authenticate AWS users.
apiVersion: iam.aws.upbound.io/v1beta1
kind: OpenIDConnectProvider
metadata:
  name: aatt-demo-openid-connect-provider
spec:
  forProvider:
    clientIdList:
      - sts.amazonaws.com
    thumbprintList:
      - 9e99a48a9960b14926bb7f3b02e22da2b0ab7280
    url: https://oidc.eks.us-east-1.amazonaws.com/id/9BBF76B7C9C6D52584F175E783DF54A4
    tags:
      Name: aatt-demo-openid-connect-provider
  providerConfigRef:
    name: aws