system: ${{ values.system }} 

service: ${{ values.service }} 

deployment:
  image:
    repository: AATT_DOCKERHUB_USERNAME/${{ values.system }}-${{ values.service }}
  labels:
    system: ${{ values.system }}
    service: ${{ values.service }}
    backstage.io/kubernetes-id: ${{ values.system }}-${{ values.service }}
    # istio: monitor

ingress:
  annotations: 
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
