query:
  ingress:
    enabled: true

    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
      alb.ingress.kubernetes.io/success-codes: '200'
      alb.ingress.kubernetes.io/healthy-threshold-count: '2'
      alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'

    hosts: 
      - ""
    pathType: Prefix

  # We do this because the cassandra db takes a while to start up. The collector adn query pods will fail to start if the db is not ready and will take a long time to retry.
  annotations:
    argocd.argoproj.io/sync-wave: "1"

# Allow recieving traces from Istio
collector:
  service:
    zipkin: 
      port: 9411
      
  # We do this because the cassandra db takes a while to start up. The collector adn query pods will fail to start if the db is not ready and will take a long time to retry.
  annotations:
    argocd.argoproj.io/sync-wave: "1"


cassandra:
  persistence:
    # To enable persistence, please see the documentation for the Cassandra chart
    enabled: true
    storageClass: "gp2"
    size: 5Gi
  config:
    cluster_size: 1
  livenessProbe:
    initialDelaySeconds: 180
    periodSeconds: 60
    timeoutSeconds: 10
    # successThreshold: 1
    # failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 180
    periodSeconds: 60
    timeoutSeconds: 10
    # successThreshold: 1
    # failureThreshold: 3
    # address: "${POD_IP}"
