apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-service
spec:
  selector:
    full-name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
